# Generated by Django 4.1.7 on 2023-03-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='customer_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='customer_name',
            new_name='name',
        ),
    ]
